name: AUR release

on:
  push:
    tags: "*"

jobs:
  homebrew:
    name: Bump AUR version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AUR_SSH_KEY }}
          known_hosts: unnecessary
      - name: Set env
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Push to AUR
        run: .github/aur/publish.sh ${{ env.GIT_TAG }}
